addons:
    apt:
        sources:
            - devian-sid
        packages:
            - binutils-dev
            - libunwind8-dev
            - g++
sudo: false
before_script:
    - rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
language: rust
rust:
    - nightly
cache:
    directories:
    - $HOME/.cargo
before-cache:
    - rm -rf $HOME/.cargo/registry
script:
  - export PATH="$PATH:/usr/bin"
  - cargo fmt -- --check
  - cargo test
